services:
  my_python_app:
    # Makes Compose look for the Dockerfile in the current folder (.) and build the image.
    build: .

    # Creates the bridge (volume) between the host machine and the container.
    # Syntax: [Host folder]:[Folder inside the container]
    volumes:
      - .:/app
